# Generated by Django 4.1.3 on 2022-12-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="author",
            new_name="following",
        ),
    ]
